### ISSUE TITLE
TablePlus not launching on Ubuntu 21.04

### ISSUE THREAD

**Issue by tylucaskelley** [TablePlus/TablePlus-Linux#116]
1. Database version (Ex: PostgreSQL 10.0): N/A

2. TablePlus version (the number on the welcome or about screen, Ex: build 81): 0.1.84

3. Linux distro (Ex: Ubuntu 18.04): Ubuntu 21.04

4. The steps to reproduce this issue:

Just launch the app, it seems to hang when launched either via GUI or command-line. When launching via the command line, the process just hangs with no log output. Hard to know what's going on without knowing where logs are stored.

![image](https://user-images.githubusercontent.com/5448759/117883391-5d3d0880-b279-11eb-96b9-3cfd19bef21f.png)

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by Yfelipe** [comment]
If you use sudo in the command-line to launch it, it will open but without the connections.

**Comment by baarkerlounger** [comment]
Can reproduce as well. Might be due to the home dir permissions changing in 21.04?

**Comment by Yfelipe** [comment]
Possibly, I did notice that there was a pop-up about the home directory when updated from 20 ->21 but tried to uninstall completely an reinstall but still same, which you would think it would fix it with a fresh install.

**Comment by huyphams** [comment]
i am not sure about the root cause. I've installed Ubuntu 21.04 on Parallels and TablePlus works perfectly. I think it could be some incompatible libs that were not updated when upgrading from 20 -> 21.

**Comment by Yfelipe** [comment]
May not be libs because when you run it through the console if it doesn't find the something it normally returns what is missing and it would also not work with sudo if lib is missing. I haven't tried a fresh install of 21 but if yours works it may be that the install on an upgraded version is not actually installing properly due to the home directory, Just guesses.

**Comment by marknuyens** [comment]
Same issue here... Was able to install & open it the first time, afterwards it seemed to have gotten stuck. Not sure if my settings have anything to do with it, as I haven't changed all that much.

...Anyone got a solution so far? :-)

**Comment by baarkerlounger** [comment]
It looks like this is only reproducible for me on the default Wayland session. On X.org it seems to launch as expected. Anyone else able to confirm that?

**Comment by shiftenterdev** [comment]
Yes, I think it's Wayland issue because in X.org it seems to launch as expected.

**Comment by jpuckett-di** [comment]
to add some details here, this doesn't seem to happen every time, which the inconsistency makes me doubt permissions as the issue.

rebooting usually fixes it and I can launch the app no problem, but just once. if the app is closed, then it will not open again, and instead just hangs from the command line as in OP

**Comment by Yfelipe** [comment]
Ya also noticed lately that sometimes it does actually work, I just got used to launching it via the console with sudo.

**Comment by marknuyens** [comment]
Any news on this? I would really want to purchase this for Ubuntu.

**Comment by gorbak25** [comment]
Same here

**Comment by huyphams** [comment]
Fixed https://github.com/TablePlus/TablePlus-Linux/issues/131

**Comment by baarkerlounger** [comment]
@huyphams I don't think #131 fixes this issue, it looks to be separate. I can still on a fresh install reproduce needing `sudo` to launch tableplus on Wayland. Without sudo it just hangs in the terminal indefinitely.

**Comment by krlmrr** [comment]
Not working for me either.

**Comment by christophmumm** [comment]
still not working
Ubuntu 21.10 
launch app -> nothing happens
launch it with command line -> error while loading shared libraries: libldap_r-2.4.so.2: cannot open shared object file: No such file or directory

**Comment by emozio** [comment]
> 1. Database version (Ex: PostgreSQL 10.0): N/A
> 2. TablePlus version (the number on the welcome or about screen, Ex: build 81): 0.1.84
> 3. Linux distro (Ex: Ubuntu 18.04): Ubuntu 21.04
> 4. The steps to reproduce this issue:
> 
> Just launch the app, it seems to hang when launched either via GUI or command-line. When launching via the command line, the process just hangs with no log output. Hard to know what's going on without knowing where logs are stored.
> 
> ![image](https://user-images.githubusercontent.com/5448759/117883391-5d3d0880-b279-11eb-96b9-3cfd19bef21f.png)
> 
> Noted: If the bug is related to data, please attach an example SQL data.

For some strange reason, I seem to get it launched after clicking the TablePlus app icon multiple times after another. Is this considered the solution? :-p Not sure though. But it works.

**Comment by roxshivamsingh** [comment]
I am a Zorin Pro user. I install tableplus of ubuntu 21 from this source https://tableplus.com/blog/2019/10/tableplus-linux-installation.html. It install successfully but, when I double on it to open app. It not opening. This app is very important for developers please do something.

![image](https://user-images.githubusercontent.com/56290347/180651714-849be959-9ca4-4db7-b670-eba13834b4bc.png)

**Comment by monuv10** [comment]
Any update

**Comment by bishwajitcadhikary** [comment]
Follow this link
[https://github.com/TablePlus/TablePlus-Linux/issues/130#issuecomment-925553064](https://github.com/TablePlus/TablePlus-Linux/issues/130#issuecomment-925553064)
